server:
#  address: http://libraryms.dev.io/
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryMS
    username: dev
    password: 2022
    
  jpa:
    hibernate:
      ddl-auto: create-drop
      
    show-sql: true
    